### ISSUE TITLE
Evict marvin from draft PR

### ISSUE THREAD

**Issue by blaggacao** [timokau/marvin-mk2#40]
_`marvin` should evict draft PRs entirely._

- Arguably, marvin's state machine is meant to kick in and push on the "last mile".
- Draft PRs are a great way to signal "don't bother looking at this yet".

Example of `awaiting_changes` - in the context of `marvin`'s state diagram - signalling a review process while being draft / [ WIP ]: https://github.com/NixOS/nixpkgs/pull/58230

----

Idea _(once marvin graduates into opt-out)_: 

- draft (thus evict) all new PRs upon creation
- kick in marvin's state machine upon an activation intent *by the author*
  - `/status needs_review` or a semantic analogon, like `/marvin go` (which has going viral potential)

**Comment by timokau** [comment]
Does this go further than https://github.com/timokau/marvin-mk2/issues/22? `awaiting_changes` seems appropriate for draft PRs. Note that `awaiting_changes` essentially takes a PR out of the triage loop.

I think most newly created PRs are "ready for review", publishing a WIP PR does happen but its not the norm.

**Comment by blaggacao** [comment]
Thanks for ref to #22!

This goes further.

Isolating and interpreting (in my understanding) the information bits:

- Draft => "don't even bother looking at this, I'm in stealth mode"
- `awaiting_changes` => "I'm in a state in marvin's state diagram which can have meanigful predecessores for the 'last mile' workflow"

So while Draft and `awaiting_changes` _could_ have semantic overlap, the present issue argues they _should not_.

Avoiding the semantic oberlap, essentially we can interpete `awaiting_changes` as follows: 

- `awaiting_changes` => "I'm in a state in marvin's state diagram _and definitely bother looking at this and check why we are not progressing **on the last mile**_" (either by the author or a helping hand)

Now, it doesn't (yet) happen very often, but by automatically setting new PRs to draft, we essentially introduce a new triage state which requires conscientious action by the author to push it out. This _might_ be a good general state flow, because it gives the author time for the "battle" with  the ofborg without appearing in reviewers search filters, yet, akin to the strict "I'm in stealth mode" interpretation.

**Comment by blaggacao** [comment]
Superseded by #49
