### ISSUE TITLE
Do not transition to awaiting_changes when another review is requested via @mention

### ISSUE THREAD

**Issue by timokau** [timokau/marvin-mk2#44]
Example: https://github.com/NixOS/nixpkgs/pull/92243#issuecomment-653746032

Maybe the transition should only happen on explicit change request. That would increase false-negatives, but that might be okay. False positives is what we should avoid here, since `awaiting_changes` takes a PR out of the triage cycle.

**Comment by blaggacao** [comment]
It might tremendously simplify the state diagram avoiding to express _forwad looking statements_ as states rather than state conditions based on _undisputable_ past events.

**Comment by timokau** [comment]
Further context favoring not transitioning on comments at all: https://github.com/timokau/marvin-mk2/issues/56

**Comment by timokau** [comment]
Fixed in #58.
