### ISSUE TITLE
Put cheat sheet with common commands on marvin website

### ISSUE THREAD

**Issue by turion** [timokau/marvin-mk2#64]
On https://github.com/apps/marvin-mk2 it would be great if there was a short list with the typical commands

**Comment by timokau** [comment]
Great idea! I totally forgot that I could put text there. That might also somewhat solve a problem I've been thinking about: When phasing out the opt-in model and incorporating the whole backlog, posting the greeting to every old PR would create a huge flood of spam in people's inboxes, presumably making people mad. At the same time not explaining the usage would be confusing to the PR authors. This could be a nice middle ground.

**Comment by timokau** [comment]
I've written a few words. What do you think?

**Comment by turion** [comment]
Great! If you want, I have a few nitpicks and structuring ideas:

## Marvin-Mk2 - Making sure your Pull Request gets a review

This is a bot with two primary purposes:

*    managing and labeling a pull-requests status, based upon who needs to take action (the author / a reviewer) and who is needed to proceed
*    triaging pull requests and automatically assigning reviewers where possible.

### As a PR author
Normally, you shouldn't need to directly interact with the bot. It will automatically add the correct labels based on your actions.

### As a reviewer
Quite a few status changes are also automatic. You may want to manually set the status to `needs_merger` when you have finished your review and would merge this yourself if you could (but do not have the privilege to do so). Try to anticipate the "merger"s feedback as well as possible, ideally no additional review should be necessary. Do so on a best-effort basis -- this is a learning process for all parties.

For more details, see the usage document. If you want to use marvin on your PRs, you currently have to explicitly opt-in since it is still experimental:

/marvin opt-in
/status needs_reviewer

Only the PR author can opt-in.

**Comment by timokau** [comment]
Good call on cleanly separating the author/reviewer instructions. I've updated the description, please review.

**Comment by timokau** [comment]
Closing this, feel free to reopen if you have more feedback.

**Comment by turion** [comment]
Sorry, I forgot to tell you that the version now looks great to me and is helpful.
