### ISSUE TITLE
Do not distinguish between '-' and '_' in /status command

### ISSUE THREAD

**Issue by wamserma** [timokau/marvin-mk2#74]
After using `opt-in` using `-` feels more natural than `_`. Accepting both avoids users doing stupid things like [here](https://github.com/NixOS/nixpkgs/pull/88629#issuecomment-656890936).

Plus, with some keyboard layouts, `-` can be entered without a modifier key, where e.g. `_` needs `-`+ Shift.

**Comment by asbachb** [comment]
I agree. I stumbled over this multiple times. Everytime I want to use marvin I need to lookup the exact command.

**Comment by timokau** [comment]
Unfortunately I don't have the bandwidth to implement all the improvements I'd like to see in the bot. See https://github.com/timokau/marvin-mk2/issues/34#issuecomment-898558265. Unless someone steps up to help with the maintenance and development, there is probably not much of a future for marvin-mk2.

**Comment by wamserma** [comment]
Bye Marvin.
