### ISSUE TITLE
Transition needs_reviewer -> awaiting_reviewer on non-author comment

### ISSUE THREAD

**Issue by timokau** [timokau/marvin-mk2#75]
https://github.com/NixOS/nixpkgs/pull/92243#issuecomment-657452598

**Comment by raboof** [comment]
I'm not sure if this makes sense as an automatic transition.

This assumes that all non-author comments either:
* request a review from a particular reviewer
* mean the commenter takes on the reviewer role

I don't think that is always the case.

If we do want to keep this automatic transition, at least we should blacklist bots such as `nixos-discourse` ;) (this happened for example at https://github.com/NixOS/nixpkgs/pull/98491#issuecomment-727857731)

**Comment by timokau** [comment]
Yes, its a very imperfect heuristic. I think one of the two is the case significantly more often then not though.

Doing nothing would require people to actively change the status. It is likely that people will sometimes (or often) not do this. That would make the "needs reviewer" queue less useful. Currently the heuristic sometimes fails, but at worst it adds a few days until marvin times it out again (as in #98491).

I'm not 100% sure about this, but lacking a better alternative I will keep it as-is for now. Please open an issue for the blacklist though, that's definitely a good idea.

**Comment by timokau** [comment]
A thought: It would be possible to have marvin post a "I assume you want to take over the reviewer role" message and make it possible to opt-out easily by leaving a thumbs-down on that message. The downside is the additional noise of course. It would be nice if GitHub had some better support for bot interactions.

A similar strategy could be used for status transitions (with reactions to the greeting).
