### ISSUE TITLE
No reaction after 20 minutes

### ISSUE THREAD

**Issue by davidak** [timokau/marvin-mk2#83]
They should at least add a label i think.

https://github.com/NixOS/nixpkgs/pull/89124#issuecomment-670702058

**Comment by timokau** [comment]
Yes, it seems like the nix-community server that it runs on is having issues. Unfortunately there is nothing I can do except wait for the admin.

Thanks for notifying me!

**Comment by timokau** [comment]
Should be up again.

**Comment by davidak** [comment]
yes, works now. instant reaction
