### ISSUE TITLE
Bot not activated if commands are in initial PR comment

### ISSUE THREAD

**Issue by turion** [timokau/marvin-mk2#87]
Have a look at this example: https://github.com/NixOS/nixpkgs/pull/98084

I needed to say the commands in a separate comment before the bot was activated.

**Comment by timokau** [comment]
Good catch, I'm surprised nobody reported this before! Will look into it eventually, but it might take a bit. I probably just need to pass the "PR created" event to the command parser.

**Comment by timokau** [comment]
Fix should be deployed now, please test and re-open if the issue persists.
